### ISSUE TITLE
Can't see the floating window next to custom simulator instances

### ISSUE THREAD

**Issue by rubenvde** [AvdLee/RocketSimApp#100]
**Describe the bug**
When I open a customised instance of an iOS simulator the floating window of the RocketSimApp doesn't stick to it/ doesn't appear. This bug only seems to happen when you create a custom iOS simulator. It may be related to #98 but I wasn't sure.

**To Reproduce**
1. Go to Xcode
2. Open a project
3. Click on the dropdown menu to select a simulator/device
4. Click on "Add Additional Simulators"
5. Add a new simulator for example an iPhone X running iOS 14.4
6. Select it in the dropdown menu mentioned before and run your app

**Expected behavior**
Next to the simulator a floating window appears to paste for example an image overlay

**Screenshots**
In this screenshot only the floating menu sticks to the iPhone 11 and skips the iPhone X instance. When the iPhone 11 simulator is closed the floating menu isn't appearing.
<img width="1213" alt="Screenshot 2021-04-12 at 14 31 13" src="https://user-images.githubusercontent.com/2741870/114394690-c6a6fa00-9b9b-11eb-89da-73c3b2eb0620.png">

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur 11.2.3
 - Version: 4.0.2

**Comment by AvdLee** [comment]
@rubenvde this is indeed due to the custom name of the Simulator. Unfortuantely, due to sandbox restrictions on macOS, RocketSim relies on the window name of the open Simulator.

As we can't map the name back to the device, we don't know where to position the floating window and it wont show up.

Therefore, I'm closing this as won't fix. You can solve this by using the regular names of Simulators. Sorry for the inconvenience!
