### ISSUE TITLE
Device Bezels not applied to recorded Gif

### ISSUE THREAD

**Issue by davidaberg** [AvdLee/RocketSimApp#136]
When I select Device Bezel it’s not applied to the Gif I record. Was expecting that but maybe it’s not supported?

**Comment by AvdLee** [comment]
Good point, it's indeed not supported right now! I'll keep this issue open for now to track this as a feature request.
Reason it's not yet added is since the GIFs are becoming less and less popular, especially since websites like GitHub now also support MP4 files in pull requests.

Makes me wonder; what is your main reason to use GIF over MP4?

**Comment by davidaberg** [comment]
Thanks for the quick reply. We are creating demos of our new views and components to showcase them in a Figma presentation. I can be wrong but it's my understanding that videos can't be used like that in Figma presentations.

**Comment by AvdLee** [comment]
This will be fixed in 9.6
