### ISSUE TITLE
Option to configure simulator status bar for screenshots/videos

### ISSUE THREAD

**Issue by coderExMachina** [AvdLee/RocketSimApp#173]
For screenshots as well as for videos it would be great if it would be possible to customize the simulators status bar. E.g. I would like to:

- Set the time format
- Set a specific time, e.g. to 09:41 😎
- Show full cellular signal

**Comment by AvdLee** [comment]
Guess what: an early version of RocketSim already had this in place. Though: it slows down the recording process since it has to run the command for updating the status bar first.

I'll re-evaluate implementing this, but I will probably make it a separate step with a potential opt-in to automate it before running a capture event.

**Comment by AvdLee** [comment]
I've been able to make this work and will ship this with 12.6.0:

<img width="860" alt="CleanShot 2024-01-26 at 22 28 57@2x" src="https://github.com/AvdLee/RocketSimApp/assets/4329185/507659e7-fe4e-4a40-999f-e1960e743255">
