### ISSUE TITLE
Style configuration on the floating window

### ISSUE THREAD

**Issue by im-jersh** [AvdLee/RocketSimApp#432]
**Is your feature request related to a problem? Please describe.**
Depending on the style of my other windows, sometimes there's not very much contrast to RocketSim's floating window when it's floating over another window, making it difficult to discern RocketSim's content especially when in the system Dark Mode is activated.

**Describe the solution you'd like**
A configurable setting that allows to tint the floating RocketSim window or maybe add a border stroke around the floating window so that the bounds of the floating window are more pronounced against any window that might be under it.

**Describe alternatives you've considered**
N/A

**Additional context**
Here's an example of RocketSim's floating window over Xcode

<img width="987" alt="Screenshot 2023-11-14 at 3 38 10 PM" src="https://github.com/AvdLee/RocketSimApp/assets/4296435/7f6ebd3f-1ec3-4789-b5d2-50fdb374053a">

While this can be easily solved remedied for Xcode by changing the theme's background color, this isn't an ideal solution nor one that can be applied across other apps such as web browsers

**Comment by AvdLee** [comment]
Thanks for reporting this, I've actually had the same idea on a private backlog. It's currently not working great and even a small white border with 0.2 opacity would make a major difference. I'll see what I can do!

**Comment by AvdLee** [comment]
This will be fixed in 12.2.0:

![CleanShot 2023-11-17 at 21 59 26@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/f409ba86-cfc6-4641-839c-f4d2d288ff02)

Or, like this:

| Before | After |
| --- | --- |
| ![CleanShot 2023-11-17 at 21 19 55@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/82c0d6c9-d7df-444e-9ef7-2b791c999dea) | ![CleanShot 2023-11-17 at 21 18 56@2x](https://github.com/AvdLee/RocketSimApp/assets/4329185/0f13a5b6-65b2-41d8-8163-07d3f6db9c3d) |

**Comment by im-jersh** [comment]
amazing, just downloaded the update and it's exactly what RocketSim needed! appreciate the quick response and release

**Comment by AvdLee** [comment]
Glad you like it @im-jersh 💪
