### ISSUE TITLE
Tapping on menu bar item hangs my M1 MacBook for multiple seconds

### ISSUE THREAD

**Issue by KaiOelfke** [AvdLee/RocketSimApp#457]
**Describe the bug**
My M1 MacBook hangs for multiple seconds and shows a beach ball after tapping on the rocket sim menu bar icon. Subsequent taps are immediate as normal. Changing the active / focused app slows down tapping the menu bar item again.

**To Reproduce**
1. Launch RocketSim
2. No Xcode running or simulator (not sure if it matters)
3. Tap on rocket sim menu bar
4. Change active app e.g. open mail or a browser
5. Repeat step 3 and 4 to reproduce multiple times

**Expected behavior**

I expect the menu bar item to always open immediately.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: 14.3 (23D56)
 - Version: Version 12.6.2 (197)

**Additional context**

**Comment by markrenaud** [comment]
I am having similar issues.  M1 Max MacBook Pro..

**Comment by AvdLee** [comment]
@markrenaud sorry for that! 

You can right-click the report an issue button to save the file to disk. That way, you can upload the DR to any email provider:

<img width="635" alt="CleanShot 2024-02-18 at 13 25 33@2x" src="https://github.com/AvdLee/RocketSimApp/assets/4329185/79cdbdf6-d771-4fcf-8a9d-0f590005384f">

Thanks a lot for helping out, I'm trying to find the cause as we speak!

**Comment by AvdLee** [comment]
Additional question: does this happen directly after a fresh launch? Or only after having RocketSIm open for a while?

**Comment by markrenaud** [comment]
Sorry for the delay in replying, and thank you for looking into the issue.

The problem can occur after a fresh launch. Simply bringing another app to the foreground before clicking on the menu bar item is enough to cause the hang.

For example:
- Start in Xcode and launch RocketSim (I do have it enabled as an 'Open at login' app) - menu bar works as expected.
- Switch to Safari - Safari is now the foreground app.
- Clicking on the menu bar for the first time with the new app in the foreground causes the hang.
- Further clicks on the menu bar item then (generally) work promptly while the same app remains in the foreground.
- Changing to another app (e.g., bringing Music to the foreground) and then clicking on the menu bar will cause the hang for the first click, with subsequent clicks in that same app being prompt to open the menu.

Interestingly, **sometimes** when switching the foreground app back to Xcode, the hang doesn't occur on the next click of the menu bar app. This behavior is unique to switching back to Xcode - switching to any other app in the foreground always causes the hang.

The hang blocks all of macOS UI (I can't even type anything anywhere, can't use Finder, etc.).

I will try to send a Diagnostics report when I get a chance.

PS. I just updated to version 12.6.5 (200), and the issue still occurs.

**Comment by AvdLee** [comment]
@markrenaud thanks a lot for those insights. A Diagnostics report would be amazing. I feel like there's some heavy main-thread work happening. Potentially, it's a network request that does work great from my machine, but might have much slower response in other regions. Thinking out loud here, but a Diagnostics Report will definitely give better insights! 🙏

**Comment by markrenaud** [comment]
I sent a diagnostics report and a video of the issue to you yesterday at the email:  support@rocketsim.app  - please let me know it this didn't come through, and I can resend to an email of your choice.

**Comment by markrenaud** [comment]
@AvdLee, just another thought - does the app scan for available run destinations (or try to probe them somehow) when you click on the menu bar? I have noticed issues with Xcode physical device run destinations that are able to "Connect via network" (in the Devices & Simulators window) being slow to resolve information in other scenarios. I wonder if this may be part of the issue - and if it is, it may be related to the issue here: https://developer.apple.com/forums/thread/737875. I was intrigued to learn in this thread that [iOS 17 has a new debugging infrastructure such that all debugging goes over the network](https://developer.apple.com/forums/thread/737875?answerId=765840022#765840022). When you mentioned a network request, I wondered what sort of network request is being sent with each click of the menu bar app icon - it got me thinking about this issue.

Please let me know if you require any further testing on my end. I'm currently working on some app functionality that requires location services, and RocketSim's ability to quickly change simulator locations is amazing (but frustrating with the hang).

**Comment by markrenaud** [comment]
Here's some additional information for you - beyond the video and diagnostics report emailed, I've also attached a spindump for RocketSim that captured a 10-second period while I was triggering the hang.

It certainly seems to be doing a lot of work during the hang: 
RocketSim: `CPU Time: 5.416s (17.0G cycles, 59.4G instructions, 0.29c/i)`

For comparison, the next closest app in terms of CPU time was ActivityMonitor (which I would expect to be doing more cycles than simply clicking on the RocketSim menu bar app).
ActivityMonitor: `CPU Time: 0.284s (358.4M cycles, 704.8M instructions, 0.51c/i)`

I'm no spindump expert, but it appears that there is a significant amount of work being done in enumerating directories when clicking on the RocketSim menu bar icon. Perhaps this directory enumeration is causing issues.

Apologies for the multiple messages.
[rocketsim-spindump.txt](https://github.com/AvdLee/RocketSimApp/files/14414361/rocketsim-spindump.txt)

**Comment by markrenaud** [comment]
@AvdLee I have emailed the requested reports and some additional information.  😄

**Comment by AvdLee** [comment]
I might have fixed your issue. I can’t narrow down exactly where it might have performance issues, but this is my hypothesis:

- I’m refreshing all applications for all Simulators up on opening the Menu Bar Menu
- I did not do any caching
- All applications would be iterated, including many file operations
- If you have many Simulators, many recent builds, the performance could be worse. This is why it didn’t occur for me since I have a low number of both

The fix I did is to cache applications and only refresh them if the modification date for the application folder changes.

I’m hoping to ship a fix in the coming days, so stay tuned!
