### ISSUE TITLE
Select Xcode doesn't work well

### ISSUE THREAD

**Issue by KaiOelfke** [AvdLee/RocketSimApp#584]
**Describe the bug**
Today I had an issue, where I was prompted several times to select Xcode. I don't know why RocketSim can't use something liek xcode-select -p. I manage my selected Xcode with Xcodes. Some days ago it was worse when the prompt kept appearing in multiple windows, which was very obtrusive. I was debugging something and didn't even want to use RocketSim and it interrupted me.

**Expected behavior**

Ideally, I don't want to do this at all. E.g. for Tuist I don't have deal with that. It checks what Xcode is selected. If I have to do it then I want to be able to do it once. I don't want to do this again, if I don't change my Xcode. I also want to be able to cancel this dialog, if I don't want to do this now. 

**Screenshots**
<img width="1050" alt="Bildschirmfoto 2024-09-18 um 11 48 12" src="https://github.com/user-attachments/assets/342067d9-8831-4581-a40a-a145a8b4e90a">

**Desktop (please complete the following information):**
 - OS: macOS Sonoma 14.6.1
 - Version: 236

**Additional context**

**Comment by KaiOelfke** [comment]
Today without changing my active Xcode in the last days I ran into this issue again. Even worse selecting Xcode 16 doesn't fix it. The prompt just comes up again. And I can't quit RocketSim to continue working. I can only force kill the process.

**Comment by AvdLee** [comment]
@KaiOelfke thanks for letting me know! This scenario happens if RocketSim is unable to recognize the Simulator. I'm going to check if we correctly support the Apple Watch shown.

> I don't know why RocketSim can't use something liek xcode-select -p.

I wish I could use that, but since I'm in the Mac App Store, this is not possible. That's the difference with other tools like Xcodes and Tuist. However, normally, RocketSim would work by just selecting an Xcode version once, which should be acceptable.

Let me know if that clarifies!

**Comment by KaiOelfke** [comment]
I definitely was prompted and selected Xcode 16 already multiple times.

> I wish I could use that, but since I'm in the Mac App Store, this is not possible. 

Ok, I get that. In my opinion you should distribute it outside then as well. Maybe there will be more limitations in the future as a developer tool. My company can't pay via the Mac App Store easily and so got a team license outside anyway on Gumroad.

**Comment by AvdLee** [comment]
The simulator issue will be fixed in 12.11.9

> Ok, I get that. In my opinion you should distribute it outside then as well. Maybe there will be more limitations in the future as a developer tool. My company can't pay via the Mac App Store easily and so got a team license outside anyway on Gumroad.

I've considered distributing outside of the App Store, but:

- It's an extra distribution channel to maintain
- The App Store Sandboxing is an extra security layer which allows me to sell to more larger companies out of the box
- With team licenses, there's no reason for me anymore

The only reason would be unforeseen limitations, like you mentioned, but so far I'm not having these yet 🙏
