### ISSUE TITLE
Artifacts and loss of color when saving recorded videos as MP4

### ISSUE THREAD

**Issue by Ariandr** [AvdLee/RocketSimApp#84]
**Describe the bug**
When saving recording in MP4 format there are artifacts. Also, in many cases videos become Black and White.
When saving as a GIF, colors are preserved.

**Expected behavior**
No artifacts and loss of color

**Screenshots**
Here is the issue with artifacts (MP4):
https://user-images.githubusercontent.com/13591333/108205401-b0496880-712d-11eb-84df-e07aec0e705e.mp4
<img width="361" alt="Screenshot at Feb 17 14-37-05" src="https://user-images.githubusercontent.com/13591333/108206235-d0c5f280-712e-11eb-807c-479bdd1ec350.png">
GIF doesn't have this issue:
![RocketSim Recording - iPhone 12 Pro - 2021-02-17 14 37 09](https://user-images.githubusercontent.com/13591333/108205450-c48d6580-712d-11eb-8aab-7e25e556fb23.gif)

Here is the issue with black and white (MP4):
https://user-images.githubusercontent.com/13591333/108204260-41b7db00-712c-11eb-8f2e-8e3b905c0f1a.mp4
https://user-images.githubusercontent.com/13591333/108204689-ca367b80-712c-11eb-8a05-227dd4bac3de.mp4
When saving as a GIF, colors are preserved too:
![RocketSim Recording - iPhone 12 Pro - 2021-02-17 14 23 27](https://user-images.githubusercontent.com/13591333/108204386-690ea800-712c-11eb-8947-2ccb7b16a244.gif)
On this screenshot, colors are normal.
<img width="483" alt="Screenshot 2021-02-17 at 14 30 05" src="https://user-images.githubusercontent.com/13591333/108204760-dfaba580-712c-11eb-9ca1-a04a3a48e275.png">

**Desktop (please complete the following information):**
 - OS: iOS 14.4 simulator, Catalina 10.15.7
 - Version: RocketSim 3.4.1

It might be only on Catalina, but I'm not sure.

**Comment by Ariandr** [comment]
I can provide more examples, the more colorful application, the more noticeable issues become.

**Comment by AvdLee** [comment]
So if I understand correctly the white is turning in green? 😮

That's not good. I'll definitely need some different exporting settings!

**Comment by Ariandr** [comment]
@AvdLee 
I found that the middle portion of the screen turns into whatever color the top/bottom parts are.
That's why when top and bottom are white, the video becomes black and white.

**Comment by fmartinsrr** [comment]
Is there any news about this issue? I would like to use the videos on the App Store but since the colors are not accurate I cannot use them.
Would be possible for you to switch to another codec or update the lib? Or is there something I can try on my side?
In attachment, I have added a screenshot of the app and the video recorded with RocketSim.

https://user-images.githubusercontent.com/53081877/115128611-dfb60d80-9fd6-11eb-8edb-edd9084f2176.mp4
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-17 at 23 43 23](https://user-images.githubusercontent.com/53081877/115128614-e47ac180-9fd6-11eb-8ab8-7133c857c171.png)

**Comment by filipemsmartins** [comment]
Is there any news about this issue? I would like to use the videos on the App Store but since the colors are not accurate I cannot use them.
Would be possible for you to switch to another codec or update the lib? Or is there something I can try on my side?
In attachment, I have added a screenshot of the app and the video recorded with RocketSim.

Rocket sim output video
https://user-images.githubusercontent.com/53081877/115128611-dfb60d80-9fd6-11eb-8edb-edd9084f2176.mp4

App screenshot
![Simulator Screen Shot - iPhone 12 Pro Max - 2021-04-17 at 23 43 23](https://user-images.githubusercontent.com/4590289/115128710-7edb0500-9fd7-11eb-8d7e-c02f283a6fed.png)

RocketSim image
![Screenshot 2021-04-17 at 23 49 34](https://user-images.githubusercontent.com/4590289/115128716-92866b80-9fd7-11eb-9aaa-a06fc9a53e2d.png)

**Comment by AvdLee** [comment]
@filipemsmartins this is very unfortunate! This issue is not consistently happening and, therefore, hard to reproduce on my side. I can't switch codecs easily because of restrictions in ASC and availabilities in the Swift APIs I'm using.

I do plan to rewrite the exporting logic to be both more performant and better in exporting. However, this means rewriting from high-level APIs to low-level APIs which comes with both a learning curve and a lot of time.

If you can send me an original output of `xcrun simctl io booted recordVideo --codec=h264 -f output.mp4` I can try to reproduce the mismatch in colors on my side and fix it accordingly.

You can send the raw video to contact@avanderlee.com.

**Comment by filipemsmartins** [comment]
@AvdLee thanks for your reply. When recording through that Xcode command I do get the same results. But then I try without specifying the codec and the output was ok. 
So, to have the record correctly the command I have used was:
`xcrun simctl io booted recordVideo output.mov`

Btw, I am running BigSur 11.2.3, Xcode 12.4, on simulator iPhone 12 Pro Max with iOS 14.4

**Comment by AvdLee** [comment]
@filipemsmartins alright, that's very valuable feedback! I should reconsider using `h264` in that case. I'll see what I can do! If it's working just as fine, I'll just reset that codec to the default.

**Comment by filipemsmartins** [comment]
@AvdLee I am glad I could help. Since this appears to be a bug on the Xcode utils, I would suggest adding an option on the RocketSim preferences to disable\enable the h264 codec. That way for users not experiencing this issue could still use that codec.

**Comment by AvdLee** [comment]
> I would suggest adding an option on the RocketSim preferences to disable\enable the h264 codec. That way for users not experiencing this issue could still use that codec.

Obviously, I've been thinking about this. However, it makes it harder for me to maintain RocketSim, as it comes with extra scenarios and possibilities.

In the end, if setting it to non-`h264` fixes this and also makes everything else work, I don't think there's a need for anyone to change the codec

**Comment by AvdLee** [comment]
Turned out that HEVC works fine as well! So if that solves the above issue, it should be fine. Submitting now, will be available later this week in the 4.1.2 update. Please, let me know when this issue returns!

**Comment by Thomvis** [comment]
Using 4.1.2 still gives me not so great video results. The colors appear washed out. You can see this if you compare the screenshot in the first tweet and the videos from the following tweets in this thread: https://twitter.com/construct5e/status/1390018544566513665.

**Comment by AvdLee** [comment]
@Thomvis are you sure this is RocketSim related and not Twitter related? Twitter is great in messing up video quality

**Comment by Thomvis** [comment]
@AvdLee I should have mentioned that, because I also doubted Twitter. But yes, the original files also have the issue: https://www.dropbox.com/s/66zqwglf2fy4cf1/dice.mp4?dl=0.

I was using Xcode 12.4's iPad Pro 12.9 inch (4th generation) simulator.

**Comment by AvdLee** [comment]
Alright, thanks for confirming that! 

Would you mind trying out the following command and verify the outcome:
```
xcrun simctl io booted recordVideo output.mov --codec h264
```

and

```
xcrun simctl io booted recordVideo output.mov --codec hevc
```

I'm curious to see how this raw output looks, whether one of them has the same issue!

**Comment by Thomvis** [comment]
@AvdLee h264 is washed out, hevc is alright. Since you switched to the latter I tried to make a video with RocketSim again and now it was alright... I must have used an older version, perhaps because the app was running during App Store update, I don't know. Sorry about that.

The video quality of the `simctl` is noticable higher though. Compare [simctl recording](https://user-images.githubusercontent.com/134170/117446822-f350f600-af3c-11eb-926c-9da6e4851fb5.mov) to [RocketSim recording](https://user-images.githubusercontent.com/134170/117446828-f64be680-af3c-11eb-9f65-85242471932b.mp4).

**Comment by AvdLee** [comment]
@Thomvis alright, great! Yeah, the quality is hard to get right with adding extra layers like touches, combined with resizing for App Store Connect App Previews.

I do plan to work on an improved formatted in a few months which should fix this!
